function entries = catalog()
% Define the study registry.

entries = [ ...
    make_entry('hybrid-ratio-response', ...
        'Adiabatic forcing scans across hybrid ratios', ...
        @presets.hybrid_ratio_response, @studies.run_continuation, ...
        'hybrid_ratio_response', 'Fig. 1', 'audited_source_refactor'), ...
    make_entry('stationary-detuning-map', ...
        'Stationary coherence maps over detuning and hybrid ratio', ...
        @presets.stationary_detuning_map, @studies.run_parameter_grid, ...
        'stationary_detuning_map', 'Fig. 2', 'audited_source_refactor'), ...
    make_entry('detuning-continuation', ...
        'Forward/backward forcing maps across detuning', ...
        @presets.detuning_continuation, @studies.run_continuation_family, ...
        'detuning_continuation', 'Fig. 3(a-c)', 'audited_source_refactor'), ...
    make_entry('stationary-hybrid-map', ...
        'Stationary coherence maps over forcing and hybrid ratio', ...
        @presets.stationary_hybrid_map, @studies.run_parameter_grid, ...
        'stationary_hybrid_map', 'Fig. 3(d-f)', 'audited_source_refactor'), ...
    make_entry('transition-boundaries', ...
        'Transition thresholds and hysteresis widths', ...
        @presets.transition_boundaries, @studies.run_transition_boundaries, ...
        'transition_boundaries', 'Fig. 4', ...
        'reconstructed_from_manuscript_parameters'), ...
    make_entry('phase-resolved-response', ...
        'Phase-resolved continuation and collective frequency', ...
        @presets.phase_resolved_response, @studies.run_continuation, ...
        'phase_resolved_response', 'Fig. 5', 'audited_source_refactor'), ...
    make_entry('coupling-response', ...
        'Forcing response across coupling strengths', ...
        @presets.coupling_response, @studies.run_continuation, ...
        'coupling_response', 'Fig. 6(a-c)', 'audited_source_refactor'), ...
    make_entry('frequency-locking', ...
        'Collective-frequency locking over forcing and coupling', ...
        @presets.frequency_locking, @studies.run_frequency_locking, ...
        'frequency_locking', 'Fig. 6(d)', 'audited_source_refactor'), ...
    make_entry('distribution-robustness', ...
        'Response robustness for Gaussian and bimodal frequencies', ...
        @presets.distribution_robustness, @studies.run_distribution_robustness, ...
        'distribution_robustness', 'Fig. 7', 'audited_source_refactor')];
end


function value = make_entry(id, description, configure, execute, ...
    output_name, manuscript_context, provenance_status)
value.id = id;
value.description = description;
value.configure = configure;
value.execute = execute;
value.output_name = output_name;
value.manuscript_context = manuscript_context;
value.provenance_status = provenance_status;
end
